// ============================================================
//  DatosParaTodos — Configuración central
//  Todos los datasets, secciones y endpoints en un solo lugar
// ============================================================

const CONFIG = {
    siteName: 'DatosParaTodos',
    siteTagline: 'Plataforma Nacional de Datos Abiertos',
    version: '1.0.0',
    backendApiBase: 'http://127.0.0.1:8000',
    // Gemini API — el usuario la ingresa en la UI
    geminiModel: 'gemini-2.0-flash',
    geminiEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
    // datos.gov.co base API (Socrata SODA)
    socrataBase: 'https://www.datos.gov.co/resource',
};

// ============================================================
//  SECCIONES — cada sección tiene su página, ícono, color y datasets
// ============================================================
const SECTIONS = [
    {
        id: 'movilidad',
        title: 'Movilidad y Transporte',
        subtitle: 'Infraestructura vial, accidentalidad y sistemas de transporte en Colombia',
        icon: '🚦',
        color: '#1a56db',
        colorLight: '#ebf2ff',
        colorDark: '#1e3a8a',
        page: 'secciones/movilidad.html',
        stats: ['Municipios cubiertos', 'Rutas activas', 'Accidentes registrados'],
        datasets: [
            {
                id: 'accidentalidad_medellin',
                title: 'Accidentalidad en Medellín',
                description: 'Registro de accidentes de tránsito en el municipio de Medellín con información de gravedad, ubicación, tipo de vehículo y condiciones al momento del accidente.',
                source: 'Alcaldía de Medellín',
                endpoint: 'https://medata.gov.co/resource/c5gk-7ypu.json',
                limit: 1000,
                tags: ['tránsito', 'seguridad vial', 'Medellín'],
                numericCols: ['gravedad', 'num_muertos', 'num_heridos'],
                dateCols: ['fecha_accidente'],
                categoryCols: ['clase_accidente', 'tipo_vehiculo', 'comuna'],
            },
            {
                id: 'transporte_fluvial',
                title: 'Transporte Fluvial Colombia',
                description: 'Estadísticas de movilización de pasajeros y carga por vías fluviales en Colombia, incluyendo principales ríos y puertos fluviales del país.',
                source: 'Ministerio de Transporte',
                endpoint: 'https://www.datos.gov.co/resource/f33e-u5sc.json',
                limit: 500,
                tags: ['fluvial', 'puertos', 'carga'],
                numericCols: ['pasajeros', 'carga_tons'],
                dateCols: ['fecha'],
                categoryCols: ['departamento', 'rio', 'tipo'],
            },
            {
                id: 'licencias_conduccion',
                title: 'Licencias de Conducción',
                description: 'Datos sobre expedición de licencias de conducción en Colombia por categoría, departamento y organismo de tránsito. Incluye renovaciones y primeras expediciones.',
                source: 'RUNT - Registro Único Nacional de Tránsito',
                endpoint: 'https://www.datos.gov.co/resource/xdk7-xrwz.json',
                limit: 800,
                tags: ['RUNT', 'conductores', 'licencias'],
                numericCols: ['total_licencias', 'renovaciones'],
                dateCols: ['fecha_expedicion'],
                categoryCols: ['departamento', 'categoria', 'organismo'],
            },
            {
                id: 'infraestructura_vial',
                title: 'Red Vial Nacional',
                description: 'Inventario y estado de la red vial nacional de Colombia incluyendo carreteras primarias, secundarias y terciarias a cargo del INVIAS.',
                source: 'INVIAS',
                endpoint: 'https://www.datos.gov.co/resource/n6wt-aafu.json',
                limit: 600,
                tags: ['vías', 'INVIAS', 'infraestructura'],
                numericCols: ['longitud_km', 'estado_numerico'],
                dateCols: ['fecha_actualizacion'],
                categoryCols: ['departamento', 'tipo_via', 'estado'],
            },
        ],
    },
    {
        id: 'medioambiente',
        title: 'Medio Ambiente y Aire',
        subtitle: 'Calidad del aire, recursos hídricos y monitoreo ambiental en el territorio colombiano',
        icon: '🌿',
        color: '#057a55',
        colorLight: '#e8f8f2',
        colorDark: '#014737',
        page: 'secciones/medioambiente.html',
        stats: ['Estaciones de monitoreo', 'Índice AQI promedio', 'Cuencas hidrográficas'],
        datasets: [
            {
                id: 'calidad_aire_bogota',
                title: 'Calidad del Aire en Bogotá',
                description: 'Mediciones horarias de contaminantes atmosféricos (PM2.5, PM10, NO2, O3, CO) en las estaciones de monitoreo de la Red de Monitoreo de Calidad del Aire de Bogotá.',
                source: 'Secretaría de Ambiente de Bogotá',
                endpoint: 'https://datosabiertos.bogota.gov.co/api/explore/v2.1/catalog/datasets/red-de-monitoreo-de-calidad-del-aire-de-bogota/records',
                limit: 1000,
                tags: ['PM2.5', 'contaminación', 'Bogotá'],
                numericCols: ['pm25', 'pm10', 'no2', 'o3'],
                dateCols: ['fecha_hora'],
                categoryCols: ['estacion', 'nivel_riesgo'],
            },
            {
                id: 'residuos_solidos',
                title: 'Gestión de Residuos Sólidos',
                description: 'Información sobre recolección, tratamiento y disposición final de residuos sólidos por municipio en Colombia. Incluye datos de reciclaje y aprovechamiento.',
                source: 'Superintendencia de Servicios Públicos',
                endpoint: 'https://www.datos.gov.co/resource/qjqf-izbt.json',
                limit: 700,
                tags: ['residuos', 'reciclaje', 'sostenibilidad'],
                numericCols: ['toneladas_recolectadas', 'porcentaje_aprovechamiento'],
                dateCols: ['periodo'],
                categoryCols: ['municipio', 'departamento', 'tipo_residuo'],
            },
            {
                id: 'areas_protegidas',
                title: 'Áreas Protegidas de Colombia',
                description: 'Registro del Sistema Nacional de Áreas Protegidas (SINAP) con información de parques nacionales, reservas naturales y otras categorías de protección ambiental.',
                source: 'Parques Nacionales Naturales',
                endpoint: 'https://www.datos.gov.co/resource/95em-uqnr.json',
                limit: 500,
                tags: ['parques', 'SINAP', 'biodiversidad'],
                numericCols: ['area_hectareas', 'visitantes_anuales'],
                dateCols: ['fecha_declaratoria'],
                categoryCols: ['categoria', 'departamento', 'ecosistema'],
            },
            {
                id: 'concesiones_agua',
                title: 'Concesiones de Agua',
                description: 'Otorgamiento de concesiones de aguas superficiales y subterráneas en Colombia por parte de las Corporaciones Autónomas Regionales.',
                source: 'Ministerio de Ambiente',
                endpoint: 'https://www.datos.gov.co/resource/m8d7-dexs.json',
                limit: 600,
                tags: ['agua', 'CAR', 'recursos hídricos'],
                numericCols: ['caudal_l_s', 'plazo_años'],
                dateCols: ['fecha_otorgamiento'],
                categoryCols: ['departamento', 'tipo_fuente', 'uso_principal'],
            },
        ],
    },
    {
        id: 'seguridad',
        title: 'Seguridad Ciudadana',
        subtitle: 'Estadísticas de criminalidad, convivencia y acciones de seguridad en Colombia',
        icon: '🛡️',
        color: '#9f1239',
        colorLight: '#fff1f2',
        colorDark: '#881337',
        page: 'secciones/seguridad.html',
        stats: ['Municipios con datos', 'Delitos registrados', 'Tasa por 100K hab.'],
        datasets: [
            {
                id: 'homicidios_colombia',
                title: 'Homicidios en Colombia',
                description: 'Estadísticas de homicidios en Colombia por municipio, año y características demográficas de las víctimas. Datos oficiales de la Policía Nacional.',
                source: 'Policía Nacional de Colombia',
                endpoint: 'https://www.datos.gov.co/resource/ha6j-pa2r.json',
                limit: 800,
                tags: ['criminalidad', 'homicidios', 'Policía'],
                numericCols: ['cantidad', 'tasa_por_100k'],
                dateCols: ['fecha'],
                categoryCols: ['departamento', 'municipio', 'genero_victima'],
            },
            {
                id: 'hurtos_personas',
                title: 'Hurto a Personas',
                description: 'Registro de delitos de hurto a personas en Colombia con información sobre modalidad, zona (urbana/rural), arma y caracterización de víctimas.',
                source: 'Fiscalía General de la Nación',
                endpoint: 'https://www.datos.gov.co/resource/y9di-q5uk.json',
                limit: 1000,
                tags: ['hurto', 'delitos', 'convivencia'],
                numericCols: ['cantidad', 'valor_bien_hurtado'],
                dateCols: ['fecha_hecho'],
                categoryCols: ['departamento', 'municipio', 'modalidad', 'zona'],
            },
            {
                id: 'violencia_intrafamiliar',
                title: 'Violencia Intrafamiliar',
                description: 'Casos de violencia intrafamiliar reportados en Colombia por departamento y municipio, con información sobre tipo de violencia y víctimas.',
                source: 'Instituto Nacional de Medicina Legal',
                endpoint: 'https://www.datos.gov.co/resource/9s4n-t7va.json',
                limit: 700,
                tags: ['violencia', 'familia', 'género'],
                numericCols: ['total_casos', 'victimas_mujeres', 'victimas_hombres'],
                dateCols: ['periodo'],
                categoryCols: ['departamento', 'municipio', 'tipo_violencia'],
            },
            {
                id: 'capturas_policiales',
                title: 'Capturas Policiales',
                description: 'Datos de capturas realizadas por la Policía Nacional en todo el territorio colombiano, clasificadas por tipo de delito, departamento y modalidad.',
                source: 'Policía Nacional de Colombia',
                endpoint: 'https://www.datos.gov.co/resource/d6yt-za9y.json',
                limit: 800,
                tags: ['capturas', 'Policía', 'delitos'],
                numericCols: ['total_capturas'],
                dateCols: ['fecha'],
                categoryCols: ['departamento', 'municipio', 'tipo_delito'],
            },
        ],
    },
    {
        id: 'economia',
        title: 'Economía y Empleo',
        subtitle: 'Precios de alimentos, mercado laboral e indicadores económicos para el ciudadano',
        icon: '📈',
        color: '#b45309',
        colorLight: '#fffbeb',
        colorDark: '#92400e',
        page: 'secciones/economia.html',
        stats: ['Canasta básica', 'Tasa de desempleo', 'Empresas registradas'],
        datasets: [
            {
                id: 'precios_sipsa',
                title: 'Precios Mayoristas (SIPSA)',
                description: 'Precios mayoristas de productos agropecuarios (frutas, verduras, carnes) en las principales plazas de mercado de Colombia.',
                source: 'DANE - SIPSA',
                endpoint: 'https://www.datos.gov.co/resource/7yit-9vun.json',
                limit: 1000,
                tags: ['precios', 'alimentos', 'DANE'],
                numericCols: ['precio_promedio', 'cantidad_kg'],
                dateCols: ['fecha'],
                categoryCols: ['producto', 'plaza_mercado', 'grupo'],
            },
            {
                id: 'empleo_dane',
                title: 'Mercado Laboral — DANE',
                description: 'Indicadores del mercado laboral colombiano: tasa de desempleo, ocupación e inactividad por dominio geográfico.',
                source: 'DANE — GEIH',
                endpoint: 'https://www.datos.gov.co/resource/phgv-a4z6.json',
                limit: 600,
                tags: ['empleo', 'desempleo', 'mercado laboral'],
                numericCols: ['tasa_desempleo', 'tasa_ocupacion', 'poblacion_ocupada'],
                dateCols: ['periodo'],
                categoryCols: ['dominio', 'sexo', 'rango_edad'],
            },
            {
                id: 'matriculas_mercantiles',
                title: 'Matrículas Mercantiles',
                description: 'Registro de nuevas empresas y matrículas mercantiles en Colombia por sector económico y tamaño.',
                source: 'Confecámaras',
                endpoint: 'https://www.datos.gov.co/resource/i2vc-tnmk.json',
                limit: 1000,
                tags: ['empresas', 'matrículas', 'Cámara de Comercio'],
                numericCols: ['total_matriculas', 'empleados'],
                dateCols: ['fecha_matricula'],
                categoryCols: ['departamento', 'sector', 'tamaño'],
            },
            {
                id: 'exportaciones',
                title: 'Exportaciones Colombianas',
                description: 'Estadísticas de exportaciones colombianas por producto, país destino y valor FOB.',
                source: 'DANE / DIAN',
                endpoint: 'https://www.datos.gov.co/resource/ba55-z8m2.json',
                limit: 800,
                tags: ['exportaciones', 'comercio exterior', 'DANE'],
                numericCols: ['valor_fob_usd', 'toneladas'],
                dateCols: ['periodo'],
                categoryCols: ['departamento', 'pais_destino', 'producto'],
            },
        ],
    },
    {
        id: 'salud',
        title: 'Salud y Bienestar',
        subtitle: 'Seguimiento epidemiológico, vacunación y servicios de salud en Colombia',
        icon: '🏥',
        color: '#0e9f6e',
        colorLight: '#ecfdf5',
        colorDark: '#065f46',
        page: 'secciones/salud.html',
        stats: ['IPS habilitadas', 'Afiliados al sistema', 'Casos reportados'],
        datasets: [
            {
                id: 'enfermedades_notificacion',
                title: 'Enfermedades SIVIGILA',
                description: 'Casos de enfermedades de notificación obligatoria (dengue, malaria, etc.) reportados en tiempo real al INS.',
                source: 'INS — SIVIGILA',
                endpoint: 'https://www.datos.gov.co/resource/s3ge-9yqd.json',
                limit: 1000,
                tags: ['epidemiología', 'SIVIGILA', 'INS'],
                numericCols: ['casos', 'fallecidos'],
                dateCols: ['semana_epidemiologica'],
                categoryCols: ['departamento', 'municipio', 'enfermedad'],
            },
            {
                id: 'cobertura_vacunacion',
                title: 'Esquemas de Vacunación',
                description: 'Coberturas de vacunación por municipio y biológico para el Plan Ampliado de Inmunizaciones (PAI).',
                source: 'Ministerio de Salud',
                endpoint: 'https://www.datos.gov.co/resource/g2h4-yxvp.json',
                limit: 800,
                tags: ['vacunación', 'PAI', 'salud pública'],
                numericCols: ['cobertura_pct', 'dosis_aplicadas'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'biologico', 'grupo_edad'],
            },
            {
                id: 'prestadores_salud',
                title: 'IPS y Centros de Salud',
                description: 'Directorio de Instituciones Prestadoras de Salud (IPS) habilitadas en Colombia por nivel de atención.',
                source: 'Ministerio de Salud — REPS',
                endpoint: 'https://www.datos.gov.co/resource/xkrs-uq8s.json',
                limit: 1000,
                tags: ['IPS', 'hospitales', 'REPS'],
                numericCols: ['capacidad_camas'],
                dateCols: ['fecha_radicacion'],
                categoryCols: ['departamento', 'municipio', 'nivel_atencion'],
            },
            {
                id: 'mortalidad_materna',
                title: 'Mortalidad Materna',
                description: 'Casos y razones de mortalidad materna por departamento, crucial para políticas de bienestar.',
                source: 'INS — Ministerio de Salud',
                endpoint: 'https://www.datos.gov.co/resource/q2xb-xkzn.json',
                limit: 500,
                tags: ['mortalidad', 'materna', 'género'],
                numericCols: ['casos', 'razon_por_100k_nacidos'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'causa_basica'],
            },
        ],
    },
    {
        id: 'educacion',
        title: 'Educación y Futuro',
        subtitle: 'Becas, calidad educativa, matrícula y deserción escolar en el país',
        icon: '🎓',
        color: '#5850ec',
        colorLight: '#f5f3ff',
        colorDark: '#3730a3',
        page: 'secciones/educacion.html',
        stats: ['Becas otorgadas', 'Matrícula total', 'Puntaje promedio'],
        datasets: [
            {
                id: 'becas_icetex',
                title: 'Histórico de Becas (ICETEX)',
                description: 'Información sobre becas otorgadas para educación superior, beneficiarios y tipos de programa.',
                source: 'ICETEX',
                endpoint: 'https://www.datos.gov.co/resource/eb6r-dfgr.json',
                limit: 1000,
                tags: ['becas', 'ICETEX', 'educación superior'],
                numericCols: ['cantidad_beneficiarios'],
                dateCols: ['año_convocatoria'],
                categoryCols: ['departamento', 'municipio', 'tipo_beca', 'genero'],
            },
            {
                id: 'resultados_saber',
                title: 'Calidad - Pruebas Saber',
                description: 'Resultados de las Pruebas Saber por establecimiento educativo y municipio.',
                source: 'ICFES',
                endpoint: 'https://www.datos.gov.co/resource/2je4-qezs.json',
                limit: 800,
                tags: ['Saber', 'ICFES', 'calidad'],
                numericCols: ['puntaje_matematicas', 'puntaje_lenguaje'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'municipio', 'grado'],
            },
            {
                id: 'matricula_educacion',
                title: 'Matrícula Estudiantil',
                description: 'Estadísticas de matrícula oficial en preescolar, primaria y secundaria.',
                source: 'Ministerio de Educación — SIMAT',
                endpoint: 'https://www.datos.gov.co/resource/nudc-7mev.json',
                limit: 1000,
                tags: ['matrícula', 'SIMAT', 'cobertura'],
                numericCols: ['total_matriculados'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'nivel', 'sector'],
            },
            {
                id: 'desercion_escolar',
                title: 'Deserción Escolar',
                description: 'Tasas de deserción por nivel educativo y municipio, clave para identificar riesgos de abandono.',
                source: 'Ministerio de Educación',
                endpoint: 'https://www.datos.gov.co/resource/62ea-vw3p.json',
                limit: 700,
                tags: ['deserción', 'permanencia', 'riesgo'],
                numericCols: ['tasa_desercion'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'municipio', 'nivel'],
            },
        ],
    },
    {
        id: 'servicios',
        title: 'Servicios y Conectividad',
        subtitle: 'Servicios públicos domiciliarios y acceso a internet en el territorio',
        icon: '⚡',
        color: '#0694a2',
        colorLight: '#ecfeff',
        colorDark: '#164e63',
        page: 'secciones/servicios.html',
        stats: ['Cobertura energía', 'Puntos WiFi', 'Acceso a internet'],
        datasets: [
            {
                id: 'internet_municipios',
                title: 'Conectividad Internet',
                description: 'Penetración de internet fijo y móvil por municipio, velocidades y tecnología.',
                source: 'MinTIC',
                endpoint: 'https://www.datos.gov.co/resource/p6ah-fbbk.json',
                limit: 1000,
                tags: ['internet', 'TIC', 'conectividad'],
                numericCols: ['penetracion_pct', 'velocidad_mbps'],
                dateCols: ['trimestre'],
                categoryCols: ['departamento', 'municipio', 'operador'],
            },
            {
                id: 'wifi_bogota',
                title: 'Zonas WiFi Gratuito - Bogotá',
                description: 'Ubicación de los puntos de conectividad gratuita a internet en la ciudad de Bogotá.',
                source: 'Alcaldía de Bogotá',
                endpoint: 'https://www.datos.gov.co/resource/46r2-v79v.json',
                limit: 800,
                tags: ['WiFi', 'Bogotá', 'gratis'],
                numericCols: [],
                dateCols: [],
                categoryCols: ['localidad', 'barrio', 'tipo_punto'],
            },
            {
                id: 'cobertura_energia',
                title: 'Energía Eléctrica',
                description: 'Índices de cobertura del servicio de energía eléctrica por municipio en Colombia.',
                source: 'UPME',
                endpoint: 'https://www.datos.gov.co/resource/dvms-qf3j.json',
                limit: 800,
                tags: ['energía', 'UPME', 'cobertura'],
                numericCols: ['cobertura_pct', 'usuarios_residenciales'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'municipio', 'operador'],
            },
            {
                id: 'acueducto_alcantarillado',
                title: 'Agua y Saneamiento',
                description: 'Cobertura de los servicios de acueducto y alcantarillado en Colombia.',
                source: 'Superintendencia de Servicios Públicos',
                endpoint: 'https://www.datos.gov.co/resource/6knn-7qs2.json',
                limit: 900,
                tags: ['agua', 'acueducto', 'saneamiento'],
                numericCols: ['cobertura_acueducto_pct', 'usuarios'],
                dateCols: ['año'],
                categoryCols: ['departamento', 'municipio', 'zona'],
            },
        ],
    },
    {
        id: 'tramites',
        title: 'Trámites y Ciudadanía',
        subtitle: 'Información sobre trámites frecuentes, entidades y servicios al ciudadano',
        icon: '📄',
        color: '#4b5563',
        colorLight: '#f3f4f6',
        colorDark: '#1f2937',
        page: 'secciones/tramites.html',
        stats: ['Trámites registrados', 'Entidades', 'Categorías'],
        datasets: [
            {
                id: 'tramites_frecuentes',
                title: 'Trámites y Servicios',
                description: 'Información general de los trámites y procedimientos administrativos más frecuentes ante entidades del Estado.',
                source: 'Gobierno Abierto Colombia',
                endpoint: 'https://www.datos.gov.co/resource/mntw-htj4.json',
                limit: 1000,
                tags: ['trámites', 'servicios', 'ciudadanía'],
                numericCols: [],
                dateCols: ['fecha_actualizacion'],
                categoryCols: ['entidad', 'departamento', 'orden_entidad', 'sector_entidad'],
            },
            {
                id: 'puntos_atencion_gob',
                title: 'Puntos de Atención',
                description: 'Ubicación y horarios de los puntos de atención presencial de diversas entidades gubernamentales.',
                source: 'Función Pública',
                endpoint: 'https://www.datos.gov.co/resource/vgs3-f5un.json',
                limit: 800,
                tags: ['puntos atención', 'entidades', 'servicios'],
                numericCols: [],
                dateCols: [],
                categoryCols: ['entidad', 'municipio', 'departamento'],
            },
            {
                id: 'concesiones_mineras',
                title: 'Concesiones y Títulos',
                description: 'Registro de títulos mineros y concesiones otorgadas por el Estado en el territorio nacional.',
                source: 'Agencia Nacional de Minería',
                endpoint: 'https://www.datos.gov.co/resource/6377-9v3w.json',
                limit: 600,
                tags: ['minería', 'títulos', 'concesiones'],
                numericCols: ['area_hectareas'],
                dateCols: ['fecha_inscripcion'],
                categoryCols: ['departamento', 'municipio', 'mineral'],
            },
            {
                id: 'oferta_institucional',
                title: 'Oferta Institucional',
                description: 'Programas y servicios ofrecidos por entidades territoriales para el bienestar de la población.',
                source: 'DNP - Kit Territorial',
                endpoint: 'https://www.datos.gov.co/resource/9p54-mkh3.json',
                limit: 800,
                tags: ['programas', 'DNP', 'servicios'],
                numericCols: [],
                dateCols: [],
                categoryCols: ['departamento', 'municipio', 'sector'],
            },
        ],
    },
];

// Export for use in all pages
if (typeof module !== 'undefined') module.exports = { CONFIG, SECTIONS };
