// ============================================================
//  DatosParaTodos â€” ConfiguraciÃ³n central
//  Todos los datasets, secciones y endpoints en un solo lugar
// ============================================================

const CONFIG = {
    siteName: 'DatosParaTodos',
    siteTagline: 'Plataforma Nacional de Datos Abiertos',
    version: '1.0.0',
    backendApiBase: 'http://127.0.0.1:8000',
    // Gemini API â€” el usuario la ingresa en la UI
    geminiModel: 'gemini-2.0-flash',
    geminiEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
    // datos.gov.co base API (Socrata SODA)
    socrataBase: 'https://www.datos.gov.co/resource',
};

// ============================================================
//  SECCIONES â€” cada secciÃ³n tiene su pÃ¡gina, Ã­cono, color y datasets
// ============================================================
const SECTIONS = [
    {
        id: 'movilidad',
        title: 'Movilidad y Transporte',
        subtitle: 'Infraestructura vial, accidentalidad y sistemas de transporte en Colombia',
        icon: 'ðŸš¦',
        color: '#1a56db',
        colorLight: '#ebf2ff',
        colorDark: '#1e3a8a',
        page: 'secciones/movilidad.html',
        stats: ['Municipios cubiertos', 'Rutas activas', 'Accidentes registrados'],
        datasets: [
            {
                id: 'accidentalidad_medellin',
                title: 'Accidentalidad en MedellÃ­n',
                description: 'Registro de accidentes de trÃ¡nsito en el municipio de MedellÃ­n con informaciÃ³n de gravedad, ubicaciÃ³n, tipo de vehÃ­culo y condiciones al momento del accidente.',
                source: 'AlcaldÃ­a de MedellÃ­n',
                endpoint: 'https://medata.gov.co/resource/c5gk-7ypu.json',
                limit: 1000,
                tags: ['trÃ¡nsito', 'seguridad vial', 'MedellÃ­n'],
                numericCols: ['gravedad', 'num_muertos', 'num_heridos'],
                dateCols: ['fecha_accidente'],
                categoryCols: ['clase_accidente', 'tipo_vehiculo', 'comuna'],
            },
            {
                id: 'transporte_fluvial',
                title: 'Transporte Fluvial Colombia',
                description: 'EstadÃ­sticas de movilizaciÃ³n de pasajeros y carga por vÃ­as fluviales en Colombia, incluyendo principales rÃ­os y puertos fluviales del paÃ­s.',
                source: 'Ministerio de Transporte',
                endpoint: 'https://www.datos.gov.co/resource/f33e-u5sc.json',
                limit: 500,
                tags: ['fluvial', 'puertos', 'carga'],
                numericCols: ['pasajeros', 'carga_tons'],
                dateCols: ['fecha'],
                categoryCols: ['departamento', 'rio', 'tipo'],
            },
            {
                id: 'licencias_conduccion',
                title: 'Licencias de ConducciÃ³n',
                description: 'Datos sobre expediciÃ³n de licencias de conducciÃ³n en Colombia por categorÃ­a, departamento y organismo de trÃ¡nsito. Incluye renovaciones y primeras expediciones.',
                source: 'RUNT - Registro Ãšnico Nacional de TrÃ¡nsito',
                endpoint: 'https://www.datos.gov.co/resource/xdk7-xrwz.json',
                limit: 800,
                tags: ['RUNT', 'conductores', 'licencias'],
                numericCols: ['total_licencias', 'renovaciones'],
                dateCols: ['fecha_expedicion'],
                categoryCols: ['departamento', 'categoria', 'organismo'],
            },
            {
                id: 'infraestructura_vial',
                title: 'Red Vial Nacional',
                description: 'Inventario y estado de la red vial nacional de Colombia incluyendo carreteras primarias, secundarias y terciarias a cargo del INVIAS.',
                source: 'INVIAS',
                endpoint: 'https://www.datos.gov.co/resource/n6wt-aafu.json',
                limit: 600,
                tags: ['vÃ­as', 'INVIAS', 'infraestructura'],
                numericCols: ['longitud_km', 'estado_numerico'],
                dateCols: ['fecha_actualizacion'],
                categoryCols: ['departamento', 'tipo_via', 'estado'],
            },
        ],
    },
    {
        id: 'medioambiente',
        title: 'Medio Ambiente y Aire',
        subtitle: 'Calidad del aire, recursos hÃ­dricos y monitoreo ambiental en el territorio colombiano',
        icon: 'ðŸŒ¿',
        color: '#057a55',
        colorLight: '#e8f8f2',
        colorDark: '#014737',
        page: 'secciones/medioambiente.html',
        stats: ['Estaciones de monitoreo', 'Ãndice AQI promedio', 'Cuencas hidrogrÃ¡ficas'],
        datasets: [
            {
                id: 'calidad_aire_bogota',
                title: 'Calidad del Aire en BogotÃ¡',
                description: 'Mediciones horarias de contaminantes atmosfÃ©ricos (PM2.5, PM10, NO2, O3, CO) en las estaciones de monitoreo de la Red de Monitoreo de Calidad del Aire de BogotÃ¡.',
                source: 'SecretarÃ­a de Ambiente de BogotÃ¡',
                endpoint: 'https://datosabiertos.bogota.gov.co/api/explore/v2.1/catalog/datasets/red-de-monitoreo-de-calidad-del-aire-de-bogota/records',
                limit: 1000,
                tags: ['PM2.5', 'contaminaciÃ³n', 'BogotÃ¡'],
                numericCols: ['pm25', 'pm10', 'no2', 'o3'],
                dateCols: ['fecha_hora'],
                categoryCols: ['estacion', 'nivel_riesgo'],
            },
            {
                id: 'residuos_solidos',
                title: 'GestiÃ³n de Residuos SÃ³lidos',
                description: 'InformaciÃ³n sobre recolecciÃ³n, tratamiento y disposiciÃ³n final de residuos sÃ³lidos por municipio en Colombia. Incluye datos de reciclaje y aprovechamiento.',
                source: 'Superintendencia de Servicios PÃºblicos',
                endpoint: 'https://www.datos.gov.co/resource/qjqf-izbt.json',
                limit: 700,
                tags: ['residuos', 'reciclaje', 'sostenibilidad'],
                numericCols: ['toneladas_recolectadas', 'porcentaje_aprovechamiento'],
                dateCols: ['periodo'],
                categoryCols: ['municipio', 'departamento', 'tipo_residuo'],
            },
            {
                id: 'areas_protegidas',
                title: 'Ãreas Protegidas de Colombia',
                description: 'Registro del Sistema Nacional de Ãreas Protegidas (SINAP) con informaciÃ³n de parques nacionales, reservas naturales y otras categorÃ­as de protecciÃ³n ambiental.',
                source: 'Parques Nacionales Naturales',
                endpoint: 'https://www.datos.gov.co/resource/95em-uqnr.json',
                limit: 500,
                tags: ['parques', 'SINAP', 'biodiversidad'],
                numericCols: ['area_hectareas', 'visitantes_anuales'],
                dateCols: ['fecha_declaratoria'],
                categoryCols: ['categoria', 'departamento', 'ecosistema'],
            },
            {
                id: 'concesiones_agua',
                title: 'Concesiones de Agua',
                description: 'Otorgamiento de concesiones de aguas superficiales y subterrÃ¡neas en Colombia por parte de las Corporaciones AutÃ³nomas Regionales.',
                source: 'Ministerio de Ambiente',
                endpoint: 'https://www.datos.gov.co/resource/m8d7-dexs.json',
                limit: 600,
                tags: ['agua', 'CAR', 'recursos hÃ­dricos'],
                numericCols: ['caudal_l_s', 'plazo_aÃ±os'],
                dateCols: ['fecha_otorgamiento'],
                categoryCols: ['departamento', 'tipo_fuente', 'uso_principal'],
            },
        ],
    },
    {
        id: 'seguridad',
        title: 'Seguridad Ciudadana',
        subtitle: 'EstadÃ­sticas de criminalidad, convivencia y acciones de seguridad en Colombia',
        icon: 'ðŸ›¡ï¸',
        color: '#9f1239',
        colorLight: '#fff1f2',
        colorDark: '#881337',
        page: 'secciones/seguridad.html',
        stats: ['Municipios con datos', 'Delitos registrados', 'Tasa por 100K hab.'],
        datasets: [
            {
                id: 'homicidios_colombia',
                title: 'Homicidios en Colombia',
                description: 'EstadÃ­sticas de homicidios en Colombia por municipio, aÃ±o y caracterÃ­sticas demogrÃ¡ficas de las vÃ­ctimas. Datos oficiales de la PolicÃ­a Nacional.',
                source: 'PolicÃ­a Nacional de Colombia',
                endpoint: 'https://www.datos.gov.co/resource/ha6j-pa2r.json',
                limit: 800,
                tags: ['criminalidad', 'homicidios', 'PolicÃ­a'],
                numericCols: ['cantidad', 'tasa_por_100k'],
                dateCols: ['fecha'],
                categoryCols: ['departamento', 'municipio', 'genero_victima'],
            },
            {
                id: 'hurtos_personas',
                title: 'Hurto a Personas',
                description: 'Registro de delitos de hurto a personas en Colombia con informaciÃ³n sobre modalidad, zona (urbana/rural), arma y caracterizaciÃ³n de vÃ­ctimas.',
                source: 'FiscalÃ­a General de la NaciÃ³n',
                endpoint: 'https://www.datos.gov.co/resource/y9di-q5uk.json',
                limit: 1000,
                tags: ['hurto', 'delitos', 'convivencia'],
                numericCols: ['cantidad', 'valor_bien_hurtado'],
                dateCols: ['fecha_hecho'],
                categoryCols: ['departamento', 'municipio', 'modalidad', 'zona'],
            },
            {
                id: 'violencia_intrafamiliar',
                title: 'Violencia Intrafamiliar',
                description: 'Casos de violencia intrafamiliar reportados en Colombia por departamento y municipio, con informaciÃ³n sobre tipo de violencia y vÃ­ctimas.',
                source: 'Instituto Nacional de Medicina Legal',
                endpoint: 'https://www.datos.gov.co/resource/9s4n-t7va.json',
                limit: 700,
                tags: ['violencia', 'familia', 'gÃ©nero'],
                numericCols: ['total_casos', 'victimas_mujeres', 'victimas_hombres'],
                dateCols: ['periodo'],
                categoryCols: ['departamento', 'municipio', 'tipo_violencia'],
            },
            {
                id: 'capturas_policiales',
                title: 'Capturas Policiales',
                description: 'Datos de capturas realizadas por la PolicÃ­a Nacional en todo el territorio colombiano, clasificadas por tipo de delito, departamento y modalidad.',
                source: 'PolicÃ­a Nacional de Colombia',
                endpoint: 'https://www.datos.gov.co/resource/d6yt-za9y.json',
                limit: 800,
                tags: ['capturas', 'PolicÃ­a', 'delitos'],
                numericCols: ['total_capturas'],
                dateCols: ['fecha'],
                categoryCols: ['departamento', 'municipio', 'tipo_delito'],
            },
        ],
    },
    {
        id: 'economia',
        title: 'EconomÃ­a y Empleo',
        subtitle: 'Precios de alimentos, mercado laboral e indicadores econÃ³micos para el ciudadano',
        icon: 'ðŸ“ˆ',
        color: '#b45309',
        colorLight: '#fffbeb',
        colorDark: '#92400e',
        page: 'secciones/economia.html',
        stats: ['Canasta bÃ¡sica', 'Tasa de desempleo', 'Empresas registradas'],
        datasets: [
            {
                id: 'precios_sipsa',
                title: 'Precios Mayoristas (SIPSA)',
                description: 'Precios mayoristas de productos agropecuarios (frutas, verduras, carnes) en las principales plazas de mercado de Colombia.',
                source: 'DANE - SIPSA',
                endpoint: 'https://www.datos.gov.co/resource/7yit-9vun.json',
                limit: 1000,
                tags: ['precios', 'alimentos', 'DANE'],
                numericCols: ['precio_promedio', 'cantidad_kg'],
                dateCols: ['fecha'],
                categoryCols: ['producto', 'plaza_mercado', 'grupo'],
            },
            {
                id: 'empleo_dane',
                title: 'Mercado Laboral â€” DANE',
                description: 'Indicadores del mercado laboral colombiano: tasa de desempleo, ocupaciÃ³n e inactividad por dominio geogrÃ¡fico.',
                source: 'DANE â€” GEIH',
                endpoint: 'https://www.datos.gov.co/resource/phgv-a4z6.json',
                limit: 600,
                tags: ['empleo', 'desempleo', 'mercado laboral'],
                numericCols: ['tasa_desempleo', 'tasa_ocupacion', 'poblacion_ocupada'],
                dateCols: ['periodo'],
                categoryCols: ['dominio', 'sexo', 'rango_edad'],
            },
            {
                id: 'matriculas_mercantiles',
                title: 'MatrÃ­culas Mercantiles',
                description: 'Registro de nuevas empresas y matrÃ­culas mercantiles en Colombia por sector econÃ³mico y tamaÃ±o.',
                source: 'ConfecÃ¡maras',
                endpoint: 'https://www.datos.gov.co/resource/i2vc-tnmk.json',
                limit: 1000,
                tags: ['empresas', 'matrÃ­culas', 'CÃ¡mara de Comercio'],
                numericCols: ['total_matriculas', 'empleados'],
                dateCols: ['fecha_matricula'],
                categoryCols: ['departamento', 'sector', 'tamaÃ±o'],
            },
            {
                id: 'exportaciones',
                title: 'Exportaciones Colombianas',
                description: 'EstadÃ­sticas de exportaciones colombianas por producto, paÃ­s destino y valor FOB.',
                source: 'DANE / DIAN',
                endpoint: 'https://www.datos.gov.co/resource/ba55-z8m2.json',
                limit: 800,
                tags: ['exportaciones', 'comercio exterior', 'DANE'],
                numericCols: ['valor_fob_usd', 'toneladas'],
                dateCols: ['periodo'],
                categoryCols: ['departamento', 'pais_destino', 'producto'],
            },
        ],
    },
    {
        id: 'salud',
        title: 'Salud y Bienestar',
        subtitle: 'Seguimiento epidemiolÃ³gico, vacunaciÃ³n y servicios de salud en Colombia',
        icon: 'ðŸ¥',
        color: '#0e9f6e',
        colorLight: '#ecfdf5',
        colorDark: '#065f46',
        page: 'secciones/salud.html',
        stats: ['IPS habilitadas', 'Afiliados al sistema', 'Casos reportados'],
        datasets: [
            {
                id: 'enfermedades_notificacion',
                title: 'Enfermedades SIVIGILA',
                description: 'Casos de enfermedades de notificaciÃ³n obligatoria (dengue, malaria, etc.) reportados en tiempo real al INS.',
                source: 'INS â€” SIVIGILA',
                endpoint: 'https://www.datos.gov.co/resource/s3ge-9yqd.json',
                limit: 1000,
                tags: ['epidemiologÃ­a', 'SIVIGILA', 'INS'],
                numericCols: ['casos', 'fallecidos'],
                dateCols: ['semana_epidemiologica'],
                categoryCols: ['departamento', 'municipio', 'enfermedad'],
            },
            {
                id: 'cobertura_vacunacion',
                title: 'Esquemas de VacunaciÃ³n',
                description: 'Coberturas de vacunaciÃ³n por municipio y biolÃ³gico para el Plan Ampliado de Inmunizaciones (PAI).',
                source: 'Ministerio de Salud',
                endpoint: 'https://www.datos.gov.co/resource/g2h4-yxvp.json',
                limit: 800,
                tags: ['vacunaciÃ³n', 'PAI', 'salud pÃºblica'],
                numericCols: ['cobertura_pct', 'dosis_aplicadas'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'biologico', 'grupo_edad'],
            },
            {
                id: 'prestadores_salud',
                title: 'IPS y Centros de Salud',
                description: 'Directorio de Instituciones Prestadoras de Salud (IPS) habilitadas en Colombia por nivel de atenciÃ³n.',
                source: 'Ministerio de Salud â€” REPS',
                endpoint: 'https://www.datos.gov.co/resource/xkrs-uq8s.json',
                limit: 1000,
                tags: ['IPS', 'hospitales', 'REPS'],
                numericCols: ['capacidad_camas'],
                dateCols: ['fecha_radicacion'],
                categoryCols: ['departamento', 'municipio', 'nivel_atencion'],
            },
            {
                id: 'mortalidad_materna',
                title: 'Mortalidad Materna',
                description: 'Casos y razones de mortalidad materna por departamento, crucial para polÃ­ticas de bienestar.',
                source: 'INS â€” Ministerio de Salud',
                endpoint: 'https://www.datos.gov.co/resource/q2xb-xkzn.json',
                limit: 500,
                tags: ['mortalidad', 'materna', 'gÃ©nero'],
                numericCols: ['casos', 'razon_por_100k_nacidos'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'causa_basica'],
            },
        ],
    },
    {
        id: 'educacion',
        title: 'EducaciÃ³n y Futuro',
        subtitle: 'Becas, calidad educativa, matrÃ­cula y deserciÃ³n escolar en el paÃ­s',
        icon: 'ðŸŽ“',
        color: '#5850ec',
        colorLight: '#f5f3ff',
        colorDark: '#3730a3',
        page: 'secciones/educacion.html',
        stats: ['Becas otorgadas', 'MatrÃ­cula total', 'Puntaje promedio'],
        datasets: [
            {
                id: 'becas_icetex',
                title: 'HistÃ³rico de Becas (ICETEX)',
                description: 'InformaciÃ³n sobre becas otorgadas para educaciÃ³n superior, beneficiarios y tipos de programa.',
                source: 'ICETEX',
                endpoint: 'https://www.datos.gov.co/resource/eb6r-dfgr.json',
                limit: 1000,
                tags: ['becas', 'ICETEX', 'educaciÃ³n superior'],
                numericCols: ['cantidad_beneficiarios'],
                dateCols: ['aÃ±o_convocatoria'],
                categoryCols: ['departamento', 'municipio', 'tipo_beca', 'genero'],
            },
            {
                id: 'resultados_saber',
                title: 'Calidad - Pruebas Saber',
                description: 'Resultados de las Pruebas Saber por establecimiento educativo y municipio.',
                source: 'ICFES',
                endpoint: 'https://www.datos.gov.co/resource/2je4-qezs.json',
                limit: 800,
                tags: ['Saber', 'ICFES', 'calidad'],
                numericCols: ['puntaje_matematicas', 'puntaje_lenguaje'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'municipio', 'grado'],
            },
            {
                id: 'matricula_educacion',
                title: 'MatrÃ­cula Estudiantil',
                description: 'EstadÃ­sticas de matrÃ­cula oficial en preescolar, primaria y secundaria.',
                source: 'Ministerio de EducaciÃ³n â€” SIMAT',
                endpoint: 'https://www.datos.gov.co/resource/nudc-7mev.json',
                limit: 1000,
                tags: ['matrÃ­cula', 'SIMAT', 'cobertura'],
                numericCols: ['total_matriculados'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'nivel', 'sector'],
            },
            {
                id: 'desercion_escolar',
                title: 'DeserciÃ³n Escolar',
                description: 'Tasas de deserciÃ³n por nivel educativo y municipio, clave para identificar riesgos de abandono.',
                source: 'Ministerio de EducaciÃ³n',
                endpoint: 'https://www.datos.gov.co/resource/62ea-vw3p.json',
                limit: 700,
                tags: ['deserciÃ³n', 'permanencia', 'riesgo'],
                numericCols: ['tasa_desercion'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'municipio', 'nivel'],
            },
        ],
    },
    {
        id: 'servicios',
        title: 'Servicios y Conectividad',
        subtitle: 'Servicios pÃºblicos domiciliarios y acceso a internet en el territorio',
        icon: 'âš¡',
        color: '#0694a2',
        colorLight: '#ecfeff',
        colorDark: '#164e63',
        page: 'secciones/servicios.html',
        stats: ['Cobertura energÃ­a', 'Puntos WiFi', 'Acceso a internet'],
        datasets: [
            {
                id: 'internet_municipios',
                title: 'Conectividad Internet',
                description: 'PenetraciÃ³n de internet fijo y mÃ³vil por municipio, velocidades y tecnologÃ­a.',
                source: 'MinTIC',
                endpoint: 'https://www.datos.gov.co/resource/p6ah-fbbk.json',
                limit: 1000,
                tags: ['internet', 'TIC', 'conectividad'],
                numericCols: ['penetracion_pct', 'velocidad_mbps'],
                dateCols: ['trimestre'],
                categoryCols: ['departamento', 'municipio', 'operador'],
            },
            {
                id: 'wifi_bogota',
                title: 'Zonas WiFi Gratuito - BogotÃ¡',
                description: 'UbicaciÃ³n de los puntos de conectividad gratuita a internet en la ciudad de BogotÃ¡.',
                source: 'AlcaldÃ­a de BogotÃ¡',
                endpoint: 'https://www.datos.gov.co/resource/46r2-v79v.json',
                limit: 800,
                tags: ['WiFi', 'BogotÃ¡', 'gratis'],
                numericCols: [],
                dateCols: [],
                categoryCols: ['localidad', 'barrio', 'tipo_punto'],
            },
            {
                id: 'cobertura_energia',
                title: 'EnergÃ­a ElÃ©ctrica',
                description: 'Ãndices de cobertura del servicio de energÃ­a elÃ©ctrica por municipio en Colombia.',
                source: 'UPME',
                endpoint: 'https://www.datos.gov.co/resource/dvms-qf3j.json',
                limit: 800,
                tags: ['energÃ­a', 'UPME', 'cobertura'],
                numericCols: ['cobertura_pct', 'usuarios_residenciales'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'municipio', 'operador'],
            },
            {
                id: 'acueducto_alcantarillado',
                title: 'Agua y Saneamiento',
                description: 'Cobertura de los servicios de acueducto y alcantarillado en Colombia.',
                source: 'Superintendencia de Servicios PÃºblicos',
                endpoint: 'https://www.datos.gov.co/resource/6knn-7qs2.json',
                limit: 900,
                tags: ['agua', 'acueducto', 'saneamiento'],
                numericCols: ['cobertura_acueducto_pct', 'usuarios'],
                dateCols: ['aÃ±o'],
                categoryCols: ['departamento', 'municipio', 'zona'],
            },
        ],
    },
    {
        id: 'tramites',
        title: 'TrÃ¡mites y CiudadanÃ­a',
        subtitle: 'InformaciÃ³n sobre trÃ¡mites frecuentes, entidades y servicios al ciudadano',
        icon: 'ðŸ“„',
        color: '#4b5563',
        colorLight: '#f3f4f6',
        colorDark: '#1f2937',
        page: 'secciones/tramites.html',
        stats: ['TrÃ¡mites registrados', 'Entidades', 'CategorÃ­as'],
        datasets: [
            {
                id: 'tramites_frecuentes',
                title: 'TrÃ¡mites y Servicios',
                description: 'InformaciÃ³n general de los trÃ¡mites y procedimientos administrativos mÃ¡s frecuentes ante entidades del Estado.',
                source: 'Gobierno Abierto Colombia',
                endpoint: 'https://www.datos.gov.co/resource/mntw-htj4.json',
                limit: 1000,
                tags: ['trÃ¡mites', 'servicios', 'ciudadanÃ­a'],
                numericCols: [],
                dateCols: ['fecha_actualizacion'],
                categoryCols: ['entidad', 'departamento', 'orden_entidad', 'sector_entidad'],
            },
            {
                id: 'puntos_atencion_gob',
                title: 'Puntos de AtenciÃ³n',
                description: 'UbicaciÃ³n y horarios de los puntos de atenciÃ³n presencial de diversas entidades gubernamentales.',
                source: 'FunciÃ³n PÃºblica',
                endpoint: 'https://www.datos.gov.co/resource/vgs3-f5un.json',
                limit: 800,
                tags: ['puntos atenciÃ³n', 'entidades', 'servicios'],
                numericCols: [],
                dateCols: [],
                categoryCols: ['entidad', 'municipio', 'departamento'],
            },
            {
                id: 'concesiones_mineras',
                title: 'Concesiones y TÃ­tulos',
                description: 'Registro de tÃ­tulos mineros y concesiones otorgadas por el Estado en el territorio nacional.',
                source: 'Agencia Nacional de MinerÃ­a',
                endpoint: 'https://www.datos.gov.co/resource/6377-9v3w.json',
                limit: 600,
                tags: ['minerÃ­a', 'tÃ­tulos', 'concesiones'],
                numericCols: ['area_hectareas'],
                dateCols: ['fecha_inscripcion'],
                categoryCols: ['departamento', 'municipio', 'mineral'],
            },
            {
                id: 'oferta_institucional',
                title: 'Oferta Institucional',
                description: 'Programas y servicios ofrecidos por entidades territoriales para el bienestar de la poblaciÃ³n.',
                source: 'DNP - Kit Territorial',
                endpoint: 'https://www.datos.gov.co/resource/9p54-mkh3.json',
                limit: 800,
                tags: ['programas', 'DNP', 'servicios'],
                numericCols: [],
                dateCols: [],
                categoryCols: ['departamento', 'municipio', 'sector'],
            },
        ],
    },
];

// Export for use in all pages
if (typeof module !== 'undefined') module.exports = { CONFIG, SECTIONS };
